# .github/workflows/main.yml

name: Run Proxy Scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # هر ۳ ساعت یک‌بار اجرا می‌شود
  workflow_dispatch: # برای اجرای دستی
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Google Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        # Install chromedriver (adjust version if necessary)
        CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1-3)
        CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json" | jq -r ".versions[] | select(.version | startswith(\"${CHROME_VERSION}\")) | .downloads.chromedriver[0].url")
        wget -N ${CHROMEDRIVER_VERSION} -P /tmp/
        unzip /tmp/chromedriver-linux64.zip -d /tmp/
        sudo mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run scraper
      run: python main.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add proxy.txt README.md
        # Check if there are changes to commit
        if ! git diff --staged --quiet; then
          git commit -m "Updated proxies and README"
          git push
        else
          echo "No changes to commit."
        fi
