name: Run Proxy Scraper and Send to Telegram

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Google Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        # ... (این بخش بدون تغییر باقی می‌ماند)

    - name: Run scraper and send to Telegram
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: python main.py

    - name: Commit and push proxy.txt
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add proxy.txt
        # فقط در صورتی کامیت کن که تغییری وجود داشته باشد
        if ! git diff --staged --quiet; then
          git commit -m "Updated proxy list"
          git push
        else
          echo "No changes to proxy.txt to commit."
        fi
